from __future__ import annotations

import re


HOST_VISION_REQUEST_SCHEMA = "host_vision.request.v1"
HOST_VISION_RESPONSE_SCHEMA = "host_vision.response.v1"
HOST_VISION_STATUS_SCHEMA = "host_vision.status.v1"
HOST_VISION_REQUEST_ID_RE = re.compile(r"^[0-9a-f]{32}$")
HOST_VISION_REQUEST_KEYS = frozenset(
    {"schema", "requestId", "createdAt", "expiresAt", "userText", "runOcr"}
)
HOST_VISION_MAX_REQUEST_BYTES = 8192
HOST_VISION_MAX_USER_TEXT_CHARS = 512
HOST_VISION_MAX_OBSERVATION_CHARS = 4000
HOST_VISION_MAX_REQUEST_TTL_SEC = 180.0
HOST_VISION_RESPONSE_TTL_SEC = 180.0
HOST_VISION_SCREENSHOT_RETENTION_SEC = 300.0


__all__ = [
    "HOST_VISION_MAX_OBSERVATION_CHARS",
    "HOST_VISION_MAX_REQUEST_BYTES",
    "HOST_VISION_MAX_REQUEST_TTL_SEC",
    "HOST_VISION_MAX_USER_TEXT_CHARS",
    "HOST_VISION_REQUEST_ID_RE",
    "HOST_VISION_REQUEST_KEYS",
    "HOST_VISION_REQUEST_SCHEMA",
    "HOST_VISION_RESPONSE_SCHEMA",
    "HOST_VISION_RESPONSE_TTL_SEC",
    "HOST_VISION_SCREENSHOT_RETENTION_SEC",
    "HOST_VISION_STATUS_SCHEMA",
]
