@echo off
if defined EVELYN_START_ENV_LOADED goto :eof
set "EVELYN_START_ENV_LOADED=1"

set "EVELYN_CORE_ROOT=%~dp0"
set "EVELYN_PROJECT_ROOT=%~dp0.."
set "EVELYN_CORE_RUNTIME=%~dp0runtime"
if defined PYTHONPATH (
    set "PYTHONPATH=%EVELYN_CORE_RUNTIME%;%PYTHONPATH%"
) else (
    set "PYTHONPATH=%EVELYN_CORE_RUNTIME%"
)

REM ===== Shared launch settings =====
if "%LLAMA_DIR%"=="" set "LLAMA_DIR=/mnt/c/Users/Admin/llama.cpp"
if "%VENV_ACT%"=="" set "VENV_ACT=source ~/venvs/vllm-env/bin/activate"

if "%MAIN_LLM_BACKEND%"=="" set "MAIN_LLM_BACKEND=vllm"
if "%MAIN_LLM_VENV_ACT%"=="" set "MAIN_LLM_VENV_ACT=source /home/sands12/venvs/evelyn-gemma4-vllm/bin/activate"
if "%MAIN_LLM_GPU%"=="" set "MAIN_LLM_GPU=1"
if "%MAIN_LLM_PORT%"=="" set "MAIN_LLM_PORT=9820"
if "%MAIN_LLM_CONTEXT%"=="" set "MAIN_LLM_CONTEXT=2048"
if "%MAIN_LLM_N_PARALLEL%"=="" set "MAIN_LLM_N_PARALLEL=1"
if "%MAIN_LLM_REASONING%"=="" set "MAIN_LLM_REASONING=off"
if "%MAIN_LLM_REASONING_BUDGET%"=="" set "MAIN_LLM_REASONING_BUDGET=0"
if "%MAIN_LLM_MODEL%"=="" set "MAIN_LLM_MODEL=ciocan/gemma-4-E4B-it-W4A16"
if "%MAIN_LLM_QUANTIZATION%"=="" set "MAIN_LLM_QUANTIZATION=gptq"
if "%MAIN_LLM_DTYPE%"=="" set "MAIN_LLM_DTYPE=bfloat16"
if "%MAIN_LLM_GPU_MEMORY_UTILIZATION%"=="" set "MAIN_LLM_GPU_MEMORY_UTILIZATION=0.60"
if "%MAIN_LLM_CHAT_TEMPLATE_CONTENT_FORMAT%"=="" set "MAIN_LLM_CHAT_TEMPLATE_CONTENT_FORMAT=openai"
if "%MAIN_LLM_ENFORCE_EAGER%"=="" set "MAIN_LLM_ENFORCE_EAGER=true"
if "%MAIN_LLM_FLASHINFER_SAMPLER%"=="" set "MAIN_LLM_FLASHINFER_SAMPLER=0"
if "%MAIN_LLM_CHAT_CONTENT_FORMAT%"=="" set "MAIN_LLM_CHAT_CONTENT_FORMAT=openai"
if "%LLM_MODEL_NAME%"=="" set "LLM_MODEL_NAME=ciocan/gemma-4-E4B-it-W4A16"

if "%SUB_LLM_GPU%"=="" set "SUB_LLM_GPU=1"
if "%SUB_LLM_PORT%"=="" set "SUB_LLM_PORT=9821"
if "%SUB_LLM_CONTEXT%"=="" set "SUB_LLM_CONTEXT=8192"
if "%SUB_LLM_REASONING_BUDGET%"=="" set "SUB_LLM_REASONING_BUDGET=96"
if "%SUB_LLM_MODEL%"=="" set "SUB_LLM_MODEL=/mnt/c/Users/Admin/llama.cpp/models/supergemma4-e4b-abliterated-Q5_K_M.gguf"
if "%SUB_LLM_N_GPU_LAYERS%"=="" set "SUB_LLM_N_GPU_LAYERS=999"
if "%SUB_LLM_THREADS%"=="" set "SUB_LLM_THREADS=8"
if "%SUB_LLM_CACHE_TYPE_K%"=="" set "SUB_LLM_CACHE_TYPE_K=q8_0"
if "%SUB_LLM_CACHE_TYPE_V%"=="" set "SUB_LLM_CACHE_TYPE_V=f16"
if "%SUMMARY_MODEL_NAME%"=="" set "SUMMARY_MODEL_NAME=supergemma4-e4b-abliterated-Q5_K_M.gguf"

if "%ROUTER_LLM_GPU%"=="" set "ROUTER_LLM_GPU=1"
if "%ROUTER_LLM_PORT%"=="" set "ROUTER_LLM_PORT=9822"
if "%ROUTER_LLM_CONTEXT%"=="" set "ROUTER_LLM_CONTEXT=1536"
if "%ROUTER_LLM_REASONING%"=="" set "ROUTER_LLM_REASONING=off"
if "%ROUTER_LLM_REASONING_BUDGET%"=="" set "ROUTER_LLM_REASONING_BUDGET=12"
if "%ROUTER_LLM_MODEL%"=="" set "ROUTER_LLM_MODEL=/home/sands12/.cache/huggingface/hub/models--unsloth--gemma-4-E2B-it-GGUF/snapshots/f064409f340b34190993560b2168133e5dbae558/gemma-4-E2B-it-UD-Q6_K_XL.gguf"

if "%OMNIVOICE_VENV%"=="" set "OMNIVOICE_VENV=C:\Users\Admin\omnivoice-server\.venv"
if "%OMNIVOICE_PROFILE_DIR%"=="" set "OMNIVOICE_PROFILE_DIR=%~dp0..\omnivoice_profiles"
if "%TTS_PORT%"=="" set "TTS_PORT=8880"
if "%TTS_GPU%"=="" set "TTS_GPU=0"
if "%TTS_DEVICE%"=="" set "TTS_DEVICE=cuda"

set "MINEFLAYER_HOST=127.0.0.1"
if "%MINEFLAYER_PORT%"=="" set "MINEFLAYER_PORT=25565"
if "%MINEFLAYER_USERNAME%"=="" set "MINEFLAYER_USERNAME=sands12@naver.com"
if "%MINEFLAYER_AUTH%"=="" set "MINEFLAYER_AUTH=microsoft"
if "%MINEFLAYER_PROFILES_FOLDER%"=="" set "MINEFLAYER_PROFILES_FOLDER=%~dp0..\bot_profiles"

if "%VOYAGER_ACTION_BACKEND%"=="" set "VOYAGER_ACTION_BACKEND=codex-gateway"
if "%VOYAGER_CODEX_GATEWAY_HOST%"=="" set "VOYAGER_CODEX_GATEWAY_HOST=127.0.0.1"
if "%VOYAGER_CODEX_GATEWAY_PORT%"=="" set "VOYAGER_CODEX_GATEWAY_PORT=8787"
if "%VOYAGER_CODEX_GATEWAY_URL%"=="" set "VOYAGER_CODEX_GATEWAY_URL=http://%VOYAGER_CODEX_GATEWAY_HOST%:%VOYAGER_CODEX_GATEWAY_PORT%/codex/action"
if "%VOYAGER_CODEX_GATEWAY_PYTHON_EXE%"=="" set "VOYAGER_CODEX_GATEWAY_PYTHON_EXE=%~dp0..\.venv-voyager\Scripts\python.exe"

if "%OPUS_ERROR_TO_SILENCE%"=="" set "OPUS_ERROR_TO_SILENCE=true"
if "%STT_USE_RAW_48K%"=="" set "STT_USE_RAW_48K=false"

if "%START_WAIT_TIMEOUT_SEC%"=="" set "START_WAIT_TIMEOUT_SEC=120"
if "%START_WAIT_INTERVAL_SEC%"=="" set "START_WAIT_INTERVAL_SEC=2"
if "%SUPERVISOR_RESTART_DELAY_SEC%"=="" set "SUPERVISOR_RESTART_DELAY_SEC=3"
