FROM nvidia/cuda:12.9.2-runtime-ubuntu24.04@sha256:6d2a0dabc50c3bf14d27fc66822b6b1f94a325807ace17bd1997762307790587

RUN apt-get update && \
    apt-get install -y --no-install-recommends ca-certificates libgomp1 && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /llama

ENV LD_LIBRARY_PATH=/llama/build/bin:/usr/local/cuda/lib64

CMD ["./build/bin/llama-server", "--version"]
